id: P1E7C87B2
initial_creation_type: input
source_metadata:
  title: Garwang Chökyi Gyaltsen
  language: bo
  description: 'Texts by and about the Fourth Shechen Rabjam, Garwang Chökyi Gyaltsen
    (gar dbang chos kyi rgyal mtshan, 1811?–1862):'
  volume:
    cbf136547d484e78b5eba5d58cf6be18:
      title: A Prayer to Guru Rinpoche That Spontaneously Fulfils All Wishes (from
        the Extremely Secret Assembly of Sugatas)
      parent: Prayers
created_at: '2022-02-28T23:21:46.857287'
last_modified_at: '2022-02-28T23:21:46.857289'
